### ISSUE TITLE
Migration to WebApi/Angular

### ISSUE THREAD

**Issue by Programmer-AD** [Newaxewas/QueReal#23]
We want to migrate all extsting code to WebApi + Angular from MVC (Razor + React)

**Comment by Newaxewas** [comment]
Old UI can be dropped
Migrate controllers to Api controllers
New UI must be on latest Angular
Authentification must be migrated to JWT
Maybe we will add some build scripts

**Comment by Newaxewas** [comment]
We will use Angular material UI
We will not use state container for now

**Comment by Newaxewas** [comment]
# Tasks

- #26 
- #27 
- #28 
- #29
- #30 
- #31

**Comment by Programmer-AD** [comment]
Task splitting approved
In fact developing of new frontend can be splitted, but we will not due to small page count
